### PR TITLE
Added OAuth registration, fixed nix flake to add rust-rover (hopefully without bugs)

### LINKED ISSUE #15: OAuth Login

### PR DESCRIPTION
**Pull request by rayyan-parkar**
resolves #15 kinda, I need to add login but cant because #4 isnt done yet

### CODE REVIEW

File: src-tauri/src/client_handler.rs [hunk 1]
```diff
@@ -131,6 +147,105 @@ impl ClientHandler {
...
+        // If the user hasn't registered, we register them
+        else {
+            // Setup client metadata
+            let url = Url::parse("https://github.com/flaxeneel2/echelon/")?;
+            let new_client_url = Localized::new(url, Vec::new());
+            let grant_types : Vec<OAuthGrantType> = vec![
+                OAuthGrantType::AuthorizationCode {
+                    redirect_uris: vec![redirect_uri.clone()],
+                } ,
+                OAuthGrantType::DeviceCode];
```
Comment (flaxeneel2) [inline src-tauri/src/client_handler.rs]: put end square bracket on new line (tiny knitpick)
